

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]


jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@v2.2
        env:
          ado_token: "p4jt2eodki6wcr77yd5p4kllrvk4rddk4omfbxbecobd3lajkona"
          ado_organization: "FlexiCharge-Org2023"
          ado_project: "X-Platfrom"
          ado_wit: "Product Backlog Item"
          ado_new_state: "New"
          ado_active_state: "Doing"
          ado_close_state: "Done"
          ado_bypassrules: true
          
      


