name: test-flexicharge-cross-platform

# Controls when the workflow will run
on:

  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "dev" ]

  pull_request:
    branches: [ "main", "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  drive:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

    - name: Node Setup
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Start Flutter environment
      uses: subosito/flutter-action@v2
      
    - name: Install junitreport package
      run: dart pub global activate junitreport

    - name: Perform tests
      run: flutter test --machine | tojunit > test-report.xml
      
    - name: Generate test report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: test-report.xml
